basePath: /
definitions:
  entities.UserAuth:
    properties:
      password:
        type: string
      userId:
        type: integer
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for DocumentAgreement Application
  title: DocumentAgreement API
paths:
  /auth/signIn:
    post:
      consumes:
      - application/json
      description: login in account
      operationId: login-account
      parameters:
      - description: string valid
        in: query
        maxLength: 10
        minLength: 5
        name: username
        type: string
      - description: string valid
        in: query
        maxLength: 10
        minLength: 5
        name: password
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: SignIn
      tags:
      - auth
  /auth/signUp:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: list info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entities.UserAuth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: SignUp
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
